--schema for data on jira
CREATE SCHEMA people;

CREATE TABLE people.data (
    id BIGINT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    birthday DATE,
    email VARCHAR(50),
    phone_no VARCHAR(20),
    country VARCHAR(50),
    time_stamp TIME
);
