--schema that stores data about dogs 
CREATE SCHEMA dogs;

CREATE TABLE dogs.data (
    dog_weight FLOAT(5,2),
    dog_name VARCHAR(50),
    dog_breed VARCHAR(50),
    owner_name VARCHAR(50),
    dog_age DATE
);
